#############################################################################
# Makefile for building: FontBuilder.app/Contents/MacOS/FontBuilder
# Generated by qmake (2.01a) (Qt 4.6.2) on: ?? ????? 17 23:27:58 2010
# Project:  FontBuilder.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/local/Qt4.6/mkspecs/macx-g++ -macx -o Makefile FontBuilder.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -arch i386 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch i386 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Qt4.6/mkspecs/macx-g++ -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/usr/include -I../../src/include -I../../src/include/freetype2 -I. -I. -F/Library/Frameworks
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch i386
LIBS          = $(SUBLIBS) -F/Library/Frameworks -L/Library/Frameworks -L/Users/andry/src/lib -lfreetype -framework QtGui -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		fontbuilder.cpp \
		colorbutton.cpp \
		fontselectframe.cpp \
		fontoptionsframe.cpp \
		fontrenderer.cpp \
		charactersframe.cpp \
		fontconfig.cpp \
		abstractlayouter.cpp \
		layoutconfig.cpp \
		layoutdata.cpp \
		layouters/linelayouter.cpp \
		layouterfactory.cpp \
		layouters/boxlayouter.cpp moc_fontbuilder.cpp \
		moc_colorbutton.cpp \
		moc_fontselectframe.cpp \
		moc_fontoptionsframe.cpp \
		moc_fontrenderer.cpp \
		moc_charactersframe.cpp \
		moc_fontconfig.cpp \
		moc_abstractlayouter.cpp \
		moc_layoutconfig.cpp \
		moc_layoutdata.cpp \
		moc_linelayouter.cpp \
		moc_layouterfactory.cpp \
		moc_boxlayouter.cpp
OBJECTS       = main.o \
		fontbuilder.o \
		colorbutton.o \
		fontselectframe.o \
		fontoptionsframe.o \
		fontrenderer.o \
		charactersframe.o \
		fontconfig.o \
		abstractlayouter.o \
		layoutconfig.o \
		layoutdata.o \
		linelayouter.o \
		layouterfactory.o \
		boxlayouter.o \
		moc_fontbuilder.o \
		moc_colorbutton.o \
		moc_fontselectframe.o \
		moc_fontoptionsframe.o \
		moc_fontrenderer.o \
		moc_charactersframe.o \
		moc_fontconfig.o \
		moc_abstractlayouter.o \
		moc_layoutconfig.o \
		moc_layoutdata.o \
		moc_linelayouter.o \
		moc_layouterfactory.o \
		moc_boxlayouter.o
DIST          = /usr/local/Qt4.6/mkspecs/common/unix.conf \
		/usr/local/Qt4.6/mkspecs/common/mac.conf \
		/usr/local/Qt4.6/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.6/mkspecs/qconfig.pri \
		/usr/local/Qt4.6/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.6/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.6/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.6/mkspecs/features/debug.prf \
		/usr/local/Qt4.6/mkspecs/features/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/x86.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.6/mkspecs/features/link_pkgconfig.prf \
		/usr/local/Qt4.6/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.6/mkspecs/features/qt.prf \
		/usr/local/Qt4.6/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.6/mkspecs/features/moc.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.6/mkspecs/features/resources.prf \
		/usr/local/Qt4.6/mkspecs/features/uic.prf \
		/usr/local/Qt4.6/mkspecs/features/yacc.prf \
		/usr/local/Qt4.6/mkspecs/features/lex.prf \
		/usr/local/Qt4.6/mkspecs/features/include_source_dir.prf \
		FontBuilder.pro
QMAKE_TARGET  = FontBuilder
DESTDIR       = 
TARGET        = FontBuilder.app/Contents/MacOS/FontBuilder

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-arch \
		i386 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile FontBuilder.app/Contents/PkgInfo FontBuilder.app/Contents/Resources/empty.lproj FontBuilder.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_fontbuilder.h ui_fontselectframe.h ui_fontoptionsframe.h ui_charactersframe.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) FontBuilder.app/Contents/MacOS/ || $(MKDIR) FontBuilder.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: FontBuilder.pro  /usr/local/Qt4.6/mkspecs/macx-g++/qmake.conf /usr/local/Qt4.6/mkspecs/common/unix.conf \
		/usr/local/Qt4.6/mkspecs/common/mac.conf \
		/usr/local/Qt4.6/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.6/mkspecs/qconfig.pri \
		/usr/local/Qt4.6/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.6/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.6/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.6/mkspecs/features/debug.prf \
		/usr/local/Qt4.6/mkspecs/features/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/x86.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.6/mkspecs/features/link_pkgconfig.prf \
		/usr/local/Qt4.6/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.6/mkspecs/features/qt.prf \
		/usr/local/Qt4.6/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.6/mkspecs/features/moc.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.6/mkspecs/features/resources.prf \
		/usr/local/Qt4.6/mkspecs/features/uic.prf \
		/usr/local/Qt4.6/mkspecs/features/yacc.prf \
		/usr/local/Qt4.6/mkspecs/features/lex.prf \
		/usr/local/Qt4.6/mkspecs/features/include_source_dir.prf \
		/Library/Frameworks/QtGui.framework/QtGui.prl \
		/Library/Frameworks/QtCore.framework/QtCore.prl
	$(QMAKE) -spec /usr/local/Qt4.6/mkspecs/macx-g++ -macx -o Makefile FontBuilder.pro
/usr/local/Qt4.6/mkspecs/common/unix.conf:
/usr/local/Qt4.6/mkspecs/common/mac.conf:
/usr/local/Qt4.6/mkspecs/common/mac-g++.conf:
/usr/local/Qt4.6/mkspecs/qconfig.pri:
/usr/local/Qt4.6/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.6/mkspecs/features/qt_config.prf:
/usr/local/Qt4.6/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.6/mkspecs/features/default_pre.prf:
/usr/local/Qt4.6/mkspecs/features/mac/default_pre.prf:
/usr/local/Qt4.6/mkspecs/features/mac/dwarf2.prf:
/usr/local/Qt4.6/mkspecs/features/debug.prf:
/usr/local/Qt4.6/mkspecs/features/default_post.prf:
/usr/local/Qt4.6/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.6/mkspecs/features/mac/x86.prf:
/usr/local/Qt4.6/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.6/mkspecs/features/link_pkgconfig.prf:
/usr/local/Qt4.6/mkspecs/features/warn_on.prf:
/usr/local/Qt4.6/mkspecs/features/qt.prf:
/usr/local/Qt4.6/mkspecs/features/unix/thread.prf:
/usr/local/Qt4.6/mkspecs/features/moc.prf:
/usr/local/Qt4.6/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.6/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.6/mkspecs/features/resources.prf:
/usr/local/Qt4.6/mkspecs/features/uic.prf:
/usr/local/Qt4.6/mkspecs/features/yacc.prf:
/usr/local/Qt4.6/mkspecs/features/lex.prf:
/usr/local/Qt4.6/mkspecs/features/include_source_dir.prf:
/Library/Frameworks/QtGui.framework/QtGui.prl:
/Library/Frameworks/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt4.6/mkspecs/macx-g++ -macx -o Makefile FontBuilder.pro

FontBuilder.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) FontBuilder.app/Contents || $(MKDIR) FontBuilder.app/Contents 
	@$(DEL_FILE) FontBuilder.app/Contents/PkgInfo
	@echo "APPL????" >FontBuilder.app/Contents/PkgInfo
FontBuilder.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) FontBuilder.app/Contents/Resources || $(MKDIR) FontBuilder.app/Contents/Resources 
	@touch FontBuilder.app/Contents/Resources/empty.lproj
	
FontBuilder.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) FontBuilder.app/Contents || $(MKDIR) FontBuilder.app/Contents 
	@$(DEL_FILE) FontBuilder.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,FontBuilder,g" -e "s,@TYPEINFO@,????,g" /usr/local/Qt4.6/mkspecs/macx-g++/Info.plist.app >FontBuilder.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/FontBuilder1.0.0 || $(MKDIR) .tmp/FontBuilder1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/FontBuilder1.0.0/ && $(COPY_FILE) --parents fontbuilder.h colorbutton.h fontselectframe.h fontoptionsframe.h fontrenderer.h charactersframe.h fontconfig.h rendererdata.h abstractlayouter.h layoutconfig.h layoutdata.h layouters/linelayouter.h layouterfactory.h layoutchar.h layouters/boxlayouter.h .tmp/FontBuilder1.0.0/ && $(COPY_FILE) --parents main.cpp fontbuilder.cpp colorbutton.cpp fontselectframe.cpp fontoptionsframe.cpp fontrenderer.cpp charactersframe.cpp fontconfig.cpp abstractlayouter.cpp layoutconfig.cpp layoutdata.cpp layouters/linelayouter.cpp layouterfactory.cpp layouters/boxlayouter.cpp .tmp/FontBuilder1.0.0/ && $(COPY_FILE) --parents fontbuilder.ui fontselectframe.ui fontoptionsframe.ui charactersframe.ui .tmp/FontBuilder1.0.0/ && (cd `dirname .tmp/FontBuilder1.0.0` && $(TAR) FontBuilder1.0.0.tar FontBuilder1.0.0 && $(COMPRESS) FontBuilder1.0.0.tar) && $(MOVE) `dirname .tmp/FontBuilder1.0.0`/FontBuilder1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/FontBuilder1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r FontBuilder.app
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_fontbuilder.cpp moc_colorbutton.cpp moc_fontselectframe.cpp moc_fontoptionsframe.cpp moc_fontrenderer.cpp moc_charactersframe.cpp moc_fontconfig.cpp moc_abstractlayouter.cpp moc_layoutconfig.cpp moc_layoutdata.cpp moc_linelayouter.cpp moc_layouterfactory.cpp moc_boxlayouter.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_fontbuilder.cpp moc_colorbutton.cpp moc_fontselectframe.cpp moc_fontoptionsframe.cpp moc_fontrenderer.cpp moc_charactersframe.cpp moc_fontconfig.cpp moc_abstractlayouter.cpp moc_layoutconfig.cpp moc_layoutdata.cpp moc_linelayouter.cpp moc_layouterfactory.cpp moc_boxlayouter.cpp
moc_fontbuilder.cpp: fontbuilder.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ fontbuilder.h -o moc_fontbuilder.cpp

moc_colorbutton.cpp: colorbutton.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ colorbutton.h -o moc_colorbutton.cpp

moc_fontselectframe.cpp: fontselectframe.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ fontselectframe.h -o moc_fontselectframe.cpp

moc_fontoptionsframe.cpp: fontoptionsframe.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ fontoptionsframe.h -o moc_fontoptionsframe.cpp

moc_fontrenderer.cpp: rendererdata.h \
		layoutchar.h \
		fontrenderer.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ fontrenderer.h -o moc_fontrenderer.cpp

moc_charactersframe.cpp: charactersframe.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ charactersframe.h -o moc_charactersframe.cpp

moc_fontconfig.cpp: fontconfig.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ fontconfig.h -o moc_fontconfig.cpp

moc_abstractlayouter.cpp: layoutchar.h \
		abstractlayouter.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ abstractlayouter.h -o moc_abstractlayouter.cpp

moc_layoutconfig.cpp: layoutconfig.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ layoutconfig.h -o moc_layoutconfig.cpp

moc_layoutdata.cpp: layoutchar.h \
		layoutdata.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ layoutdata.h -o moc_layoutdata.cpp

moc_linelayouter.cpp: abstractlayouter.h \
		layoutchar.h \
		layouters/linelayouter.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ layouters/linelayouter.h -o moc_linelayouter.cpp

moc_layouterfactory.cpp: abstractlayouter.h \
		layoutchar.h \
		layouterfactory.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ layouterfactory.h -o moc_layouterfactory.cpp

moc_boxlayouter.cpp: abstractlayouter.h \
		layoutchar.h \
		layouters/boxlayouter.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ layouters/boxlayouter.h -o moc_boxlayouter.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_fontbuilder.h ui_fontselectframe.h ui_fontoptionsframe.h ui_charactersframe.h
compiler_uic_clean:
	-$(DEL_FILE) ui_fontbuilder.h ui_fontselectframe.h ui_fontoptionsframe.h ui_charactersframe.h
ui_fontbuilder.h: fontbuilder.ui \
		fontselectframe.h \
		fontoptionsframe.h \
		charactersframe.h
	/Developer/Tools/Qt/uic fontbuilder.ui -o ui_fontbuilder.h

ui_fontselectframe.h: fontselectframe.ui
	/Developer/Tools/Qt/uic fontselectframe.ui -o ui_fontselectframe.h

ui_fontoptionsframe.h: fontoptionsframe.ui
	/Developer/Tools/Qt/uic fontoptionsframe.ui -o ui_fontoptionsframe.h

ui_charactersframe.h: charactersframe.ui
	/Developer/Tools/Qt/uic charactersframe.ui -o ui_charactersframe.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp fontbuilder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

fontbuilder.o: fontbuilder.cpp fontbuilder.h \
		ui_fontbuilder.h \
		charactersframe.h \
		fontoptionsframe.h \
		fontselectframe.h \
		fontconfig.h \
		fontrenderer.h \
		rendererdata.h \
		layoutchar.h \
		layoutconfig.h \
		layoutdata.h \
		layouterfactory.h \
		abstractlayouter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fontbuilder.o fontbuilder.cpp

colorbutton.o: colorbutton.cpp colorbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o colorbutton.o colorbutton.cpp

fontselectframe.o: fontselectframe.cpp fontselectframe.h \
		ui_fontselectframe.h \
		fontconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fontselectframe.o fontselectframe.cpp

fontoptionsframe.o: fontoptionsframe.cpp fontoptionsframe.h \
		ui_fontoptionsframe.h \
		fontconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fontoptionsframe.o fontoptionsframe.cpp

fontrenderer.o: fontrenderer.cpp fontrenderer.h \
		rendererdata.h \
		layoutchar.h \
		fontconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fontrenderer.o fontrenderer.cpp

charactersframe.o: charactersframe.cpp charactersframe.h \
		ui_charactersframe.h \
		fontconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o charactersframe.o charactersframe.cpp

fontconfig.o: fontconfig.cpp fontconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fontconfig.o fontconfig.cpp

abstractlayouter.o: abstractlayouter.cpp abstractlayouter.h \
		layoutchar.h \
		layoutdata.h \
		layoutconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o abstractlayouter.o abstractlayouter.cpp

layoutconfig.o: layoutconfig.cpp layoutconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o layoutconfig.o layoutconfig.cpp

layoutdata.o: layoutdata.cpp layoutdata.h \
		layoutchar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o layoutdata.o layoutdata.cpp

linelayouter.o: layouters/linelayouter.cpp layouters/linelayouter.h \
		abstractlayouter.h \
		layoutchar.h \
		rendererdata.h \
		layoutdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linelayouter.o layouters/linelayouter.cpp

layouterfactory.o: layouterfactory.cpp layouterfactory.h \
		abstractlayouter.h \
		layoutchar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o layouterfactory.o layouterfactory.cpp

boxlayouter.o: layouters/boxlayouter.cpp layouters/boxlayouter.h \
		abstractlayouter.h \
		layoutchar.h \
		layoutdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o boxlayouter.o layouters/boxlayouter.cpp

moc_fontbuilder.o: moc_fontbuilder.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fontbuilder.o moc_fontbuilder.cpp

moc_colorbutton.o: moc_colorbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_colorbutton.o moc_colorbutton.cpp

moc_fontselectframe.o: moc_fontselectframe.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fontselectframe.o moc_fontselectframe.cpp

moc_fontoptionsframe.o: moc_fontoptionsframe.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fontoptionsframe.o moc_fontoptionsframe.cpp

moc_fontrenderer.o: moc_fontrenderer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fontrenderer.o moc_fontrenderer.cpp

moc_charactersframe.o: moc_charactersframe.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_charactersframe.o moc_charactersframe.cpp

moc_fontconfig.o: moc_fontconfig.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fontconfig.o moc_fontconfig.cpp

moc_abstractlayouter.o: moc_abstractlayouter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_abstractlayouter.o moc_abstractlayouter.cpp

moc_layoutconfig.o: moc_layoutconfig.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_layoutconfig.o moc_layoutconfig.cpp

moc_layoutdata.o: moc_layoutdata.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_layoutdata.o moc_layoutdata.cpp

moc_linelayouter.o: moc_linelayouter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_linelayouter.o moc_linelayouter.cpp

moc_layouterfactory.o: moc_layouterfactory.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_layouterfactory.o moc_layouterfactory.cpp

moc_boxlayouter.o: moc_boxlayouter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_boxlayouter.o moc_boxlayouter.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

